### ISSUE TITLE
[PATHFINDING] - Enemigos no pueden acceder a una esquina del mapa

### ISSUE THREAD

**Issue by TomasJPereyra64** [InsaneFury/FastFoodNightmares#1]
Hay una ubicación en el mapa en la cual los enemigos no pueden acceder y se acumulan infinitamente.

Pasos para reproducir:
 - Iniciar una partida en cualquier dificultad 
 - Colocarse detrás de la mesa en la esquina inferior izquierda 

Resultado: Los enemigos empezaran a acumularse a los costados de la mesa, pero nunca pueden alcanzar al jugador.

Frecuencia de reproducción: Cada vez.

Link al bug: https://drive.google.com/open?id=1NhrPJZS0J5OJAybREz2d3c6cJs-pLJHi

**Comment by InsaneFury** [comment]
Se cambio el level design para la v0.12
