### ISSUE TITLE
[A-PHASE] La barra de habilidades no se rellena al reiniciar partida

### ISSUE THREAD

**Issue by TomasJPereyra64** [InsaneFury/FastFoodNightmares#2]
Cada vez que se reinicia una partida, la barra de habilidades sigue igual que en la partida anterior.

Pasos para reproducir:
 - Morir en cualquier dificultad
 - Darle al botón de re intentar

Resultado: El juego se reinicia, pero la barra de habilidades sigue con el mismo valor que la partida anterior.

Frecuencia de reproducción: Cada vez.

Link al bug: https://drive.google.com/open?id=1-dyb8PsbJ8-4lavgQrxJ6U5pNwHSPZ_7

**Comment by undertaker725** [comment]
La barra de habilidades ahora se rellena cuando reinicias la partida,el error fue corregido en la versión 0.11
