### ISSUE TITLE
[A-PHASE] Orbes de enemigos siguen en el mapa al reiniciar partida

### ISSUE THREAD

**Issue by TomasJPereyra64** [InsaneFury/FastFoodNightmares#3]
Los orbes dejados por los enemigos muertos siguen en el mapa aun después de reiniciar.

Pasos para reproducir:
 - Morir en cualquier dificultad
 - Darle al botón de re intentar

Resultado: El juego se reinicia, pero los orbes dejados en la partida anterior siguen existiendo.

Frecuencia de reproducción: Cada vez.

Link al bug: https://drive.google.com/open?id=19IggVoA2vzh7P1-5X74WooqNZ8dHKjMK

**Comment by InsaneFury** [comment]
Fixed
