### ISSUE TITLE
[A-PHASE] Correr y disparar con la "Machine Gun" causa que el modelo del jugador se clipee

### ISSUE THREAD

**Issue by TomasJPereyra64** [InsaneFury/FastFoodNightmares#4]
Pasos para reproducir:
 - Seleccionar la "Machine Gun"
 - Presionar el botón de correr y disparar a la vez

Resultado: El jugador comenzara a moverse y disparar causando un clipeo entre las animaciones.

Frecuencia de reproducción: Cada vez.

Link al bug: https://drive.google.com/open?id=1uDSH7t7T-ihu-d7XG4bqVIIvaZvpZXlY

**Comment by InsaneFury** [comment]
Fixed
