### ISSUE TITLE
[SUGGESTION] Las oleadas empiezan muy rapido

### ISSUE THREAD

**Issue by TomasJPereyra64** [InsaneFury/FastFoodNightmares#8]
Llegado a una determinada oleada, las oleadas comienzan a superponerse entre si, haciendo que sea casi imposible tener un momento para parar de moverse y disparar.

**Comment by InsaneFury** [comment]
Es porque existen 3 modos de juego y justo el que se dejo puesto es frenetic survivial donde las oleadas no te esperan para aumentar la dificultad, luego existe un modo de juego donde las oleadas arrancan una vez eliminaste a los enemigos del mapa y otro que es como un modo historia.
