### ISSUE TITLE
A partir de la oleada 40 el rendimiento del juego baja

### ISSUE THREAD

**Issue by undertaker725** [InsaneFury/FastFoodNightmares#9]
En la dificultad, pimiento del padron y red habanero si te quedas detrás de la mesa en la esquina inferior izquierda y logras resistir hasta la oleada 40 el juego comenzara a funcionar mas lento por la cantidad de enemigos acumulados en esa parte del mapa sin embargo en la dificultad ghost pepper el rendimiento baja en la oleada 30. 
https://drive.google.com/file/d/1pRYR6Sdtd0jwXrcHx089PL8XqbHt03bA/view?usp=sharing

https://drive.google.com/file/d/1vU2TPrtkcGuYljpdX-IdPaGvyG9OHotl/view?usp=sharing

https://drive.google.com/file/d/136cDhymsn50bm3oVe-SymYiiDCR4x81U/view?usp=sharing

**Comment by InsaneFury** [comment]
Fixed! :)
